### ISSUE TITLE
EPIC - Sonataflow management console

### ISSUE THREAD

**Issue by paulovmr** [apache/incubator-kie-issues#1059]
- [x] https://github.com/apache/incubator-kie-issues/issues/1060
 - [x] https://github.com/apache/incubator-kie-issues/issues/1061
 - [x] https://github.com/apache/incubator-kie-issues/issues/1126
 - [x] https://github.com/apache/incubator-kie-issues/issues/1288
