### ISSUE TITLE
EPIC - Add theme support to UI components and improve user experience with themes

### ISSUE THREAD

**Issue by handreyrc** [apache/incubator-kie-issues#1063]
- [x] https://github.com/apache/incubator-kie-tools/issues/2215
- [x] https://github.com/apache/incubator-kie-tools/issues/2216
- [x] https://github.com/apache/incubator-kie-tools/issues/2217

**Comment by handreyrc** [comment]
Theme support for the legacy editor complete and released.
This is an old issue.
