### ISSUE TITLE
EPIC - SWF Diagram Editor in ts / react (Milestone 0)

### ISSUE THREAD

**Issue by handreyrc** [apache/incubator-kie-issues#1127]
*Summary*
-----

This Epic encompasses the Milestone 0 tasks for the new SWF Editor based on ts / react / reactflow.

It cannot be considered a MVP once it does not implement all the functionalities and UX of the current editor.
The idea is to use this functional end-to-end to gather feedback and also use it as foundation to move forward with an MVP by customizing nodes and edges and adding functionalities on top of it.

What is not supported in this Milestone:

- Evelope, Integration API to embed e distribute the editor among the multiple channels (VsCode / Standalone / Combined editor)
- UX customization for nodes and edges and associated features such as icons, tooltips, styles...

*Goals*
-----

The goal is to deliver a completely functional environment covering the basic end-to-end for the new SW diagram editor. 

*Description*
-----

In order to get a functional end-to-end the following requirements must be addressed: 
- Storybook integration for running the application, load and visualize diagrams and testing purposes 
- Marshalling / umarshalling in order to get a valid model instance from JSON / YAML raw content that later can be rendered as a diagram
- Full Model support linked to react flow nodes and edges types. Basic reanderable shapes and lines shall be created for now to represent the different types of nodes and edges. (Final UX look&Feel and associated features won't be imlemented in this interation).
- Cache and performance optimizations inherited from the original DMN editor implementation
- SWF spec 0.8  do not store node positions in JSON /YAML so an auto-layout engine is necessary in order to position nodes and edges properly in the canvas

*Tasks in this Epic*
-----

All tasks listed below shall be delivered together for this first milestone. These tasks interdependent, otherwise it won't be possible to deliver a functional end-to-end scenario that can be assessed properly.  

 - [x] https://github.com/apache/incubator-kie-issues/issues/1128
 - [x] https://github.com/apache/incubator-kie-issues/issues/1129
 - [x] https://github.com/apache/incubator-kie-issues/issues/1631
 - [x] https://github.com/apache/incubator-kie-issues/issues/1653
 - [x] https://github.com/apache/incubator-kie-issues/issues/1652
 - [x] https://github.com/apache/incubator-kie-issues/issues/1641
 - [x] https://github.com/apache/incubator-kie-issues/issues/1642
 - [x] https://github.com/apache/incubator-kie-issues/issues/1660
 - [x] https://github.com/apache/incubator-kie-issues/issues/1663
 - [x] https://github.com/apache/incubator-kie-issues/issues/1644
 - [x]  https://github.com/apache/incubator-kie-issues/issues/2058
