### ISSUE TITLE
EPIC - Create release automations

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#1231]
See https://docs.google.com/document/d/1t-08b970i9PMBy-TSM64x0RUH46pzwnIhEi-LVeL0lg/edit 
- [x] https://github.com/apache/incubator-kie-issues/issues/1238
- [x] #815
- [x] https://github.com/apache/incubator-kie-issues/issues/964
- [x] https://github.com/apache/incubator-kie-issues/issues/1237
- [x] https://github.com/apache/incubator-kie-issues/issues/1245
- [ ] (TDB)
