### ISSUE TITLE
EPIC - CNCF Serverless Workflow new DSL

### ISSUE THREAD

**Issue by fjtirado** [apache/incubator-kie-issues#1247]
This epic has been created to track all issues related with [DSL](https://github.com/serverlessworkflow/specification/issues/843) changes on Serverless Workflow spec. 

- [x] https://github.com/serverlessworkflow/sdk-java/issues/359
- [x] https://github.com/serverlessworkflow/specification/issues/856
- [x] https://github.com/serverlessworkflow/sdk-java/issues/370
- [x] https://github.com/serverlessworkflow/sdk-java/issues/380
- [x] https://github.com/serverlessworkflow/sdk-java/issues/379
- [x] https://github.com/serverlessworkflow/sdk-java/issues/418
- [x] https://github.com/serverlessworkflow/sdk-java/issues/444
- [x] https://github.com/serverlessworkflow/sdk-java/issues/449

**Comment by fjtirado** [comment]
SDK work completed. 
Created EPIC for tracking work related with reference implementation https://github.com/serverlessworkflow/sdk-java/issues/459
