### ISSUE TITLE
EPIC - Webapp for data-index, job-service deployments and workflows endpoint

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-issues#1327]
Create 3 web apps as landing pages:
- [x] https://github.com/apache/incubator-kie-issues/issues/1027
- [x] https://github.com/apache/incubator-kie-issues/issues/1028
- [x] https://github.com/apache/incubator-kie-tools/issues/3241
- [x] https://github.com/apache/incubator-kie-tools/issues/2982
