### ISSUE TITLE
EPIC - Enforce reproducible build on Maven artifacts

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#1346]
Enforce reproducible build during PR

1. create `reproducible-build` profile to be activated by `reproducible` flag (-Dreproducible) inside poms
2. adapt pr yaml to enable it

- [x] https://github.com/apache/incubator-kie-issues/issues/1347
- [x] https://github.com/apache/incubator-kie-issues/issues/1348
- [x] https://github.com/apache/incubator-kie-issues/issues/1349
- [x] https://github.com/apache/incubator-kie-issues/issues/1352

@mariofusco @porcelli @baldimir @yesamer @pefernan
