### ISSUE TITLE
EPIC - Knative CLI Plugin advancement plan

### ISSUE THREAD

**Issue by treblereel** [apache/incubator-kie-issues#1359]
Next milestone of KN Workflow CLI plugin. Comprehends:

- [x] https://github.com/apache/incubator-kie-issues/issues/1337
- [x] https://github.com/apache/incubator-kie-issues/issues/1336
- [x] https://github.com/apache/incubator-kie-issues/issues/1335
- [x] https://github.com/apache/incubator-kie-issues/issues/1334
- [x] https://github.com/apache/incubator-kie-issues/issues/1362
- [x] https://github.com/apache/incubator-kie-issues/issues/1324
- [x] https://github.com/apache/incubator-kie-issues/issues/1299
- [x] https://github.com/apache/incubator-kie-issues/issues/1361
