### ISSUE TITLE
EPIC - Continuous improvements for the DMN Editor (2H2024 iteration)

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#1419]
Prev: https://github.com/apache/incubator-kie-issues/issues/625

### Q3
- [x] https://github.com/apache/incubator-kie-issues/issues/1147
- [x] https://github.com/apache/incubator-kie-issues/issues/981
- [x] https://github.com/apache/incubator-kie-issues/issues/982
- [x] https://github.com/apache/incubator-kie-issues/issues/980
- [x] #886

### Q4
- None

**Comment by tiagobento** [comment]
Closed for 2H2024. Next iteration here: https://github.com/apache/incubator-kie-issues/issues/1759
