### ISSUE TITLE
EPIC - Knative CLI Plugin 2024 - Q4

### ISSUE THREAD

**Issue by treblereel** [apache/incubator-kie-issues#1524]
Next milestone of KN Workflow CLI plugin. Comprehends:

- [x] https://github.com/apache/incubator-kie-tools/issues/2601
- [x] https://github.com/apache/incubator-kie-issues/issues/1549
- [ ] \(Optional) https://github.com/apache/incubator-kie-tools/issues/2630
- [ ] \(Optional) https://github.com/apache/incubator-kie-issues/issues/1526

**Comment by treblereel** [comment]
Optional issues are moved to https://github.com/apache/incubator-kie-issues/issues/1583
