### ISSUE TITLE
EPIC - Issues found during Apache KIE 10.0.0 release candidates verification/votes

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#1525]
Many community members helped with verifying the artifacts for 10.0.0 release candidates [1]. Thank you ALL for your involvement and dedication! ~As much as no hard blockers have been found at the moment, many small issues could be addressed to smooth things out a little bit.~ Here's a compilation of problems I found during my verification, together with issues that other people found during theirs.

### Required by IPMC

> _See IPMC [VOTE] thread for RC1: -didn't pass [internal vote](https://lists.apache.org/thread/fr77w51gbhbfprxdybqvr7gh5163p3mz)-_
> _See IPMC [VOTE] thread for RC2 (canceled): https://lists.apache.org/thread/oz1xfz48jwlw05sdy0wvtnrhn27jc72h_
> _See IPMC [VOTE] thread for RC3 (canceled): https://lists.apache.org/thread/nrq50szwx37doopb23wyq33v0t3bbccg_
> _See IPMC [VOTE] thread for RC4 (passed): https://lists.apache.org/thread/s5sqz2nob8sqmr0gs8qnthp6gt0r36vp_

- [x] #1531
- [x] #1532
- [x] #1533
- [x] #1534
- [x] https://github.com/apache/incubator-kie-issues/issues/1616 : "NOTICE and LICENSE" in other repos are handled by
    - [x] https://github.com/apache/incubator-kie-optaplanner/pull/3130
    - [x] https://github.com/apache/incubator-kie-kogito-runtimes/pull/3714
    - [x] https://github.com/apache/incubator-kie-kogito-apps/pull/2111
    - [x] https://github.com/apache/incubator-kie-tools/pull/2746
- [x] https://github.com/apache/incubator-kie-issues/issues/1618
- [x] https://github.com/apache/incubator-kie-issues/issues/1634

### Nice to have
1. `drools-docs` failed on a first run when trying to install Node.js 16 (EOL). We should not only upgrade Node.js to 20 (LTS) but also try and understand what is causing it to fail for the first time.
  -> `drools-docs` will be excluded from the source distribution: https://github.com/apache/incubator-kie-drools/pull/6155#issuecomment-2483253000
2. Extra argument `-Dquarkus.native.additional-build-args=-H:-CheckToolchain` needed when building `kogito-apps` on Arm-based MacBook Pro, with `graalvm-jdk-17.0.12+8.1`.
4. `kie-tools` build got stuck on a prompt from Angular about collecting analytics. We need to have this disabled by default.
5. ~Make "Build instructions" and "How to verify" sections tied to a release. Those instructions will likely change from one release to the other.~ Moved to https://github.com/apache/incubator-kie-issues/issues/1689
6. `999-SNAPSHOT` references found on disabled modules on `kogito-runtimes@10.0.0` (dead code)
7. ✅ FIXED: ~https://github.com/apache/incubator-kie-issues/issues/1602~
8. `helm-docs` is not listed as a requirement before building 10.0.0 from source.

---

9. ✅ FIXED: ~`kogito-images` copying the entire local Maven repository (`~/.m2/repository`) inside Container images during build, causing build to fail for people with a large local Maven repository.~ (see https://github.com/apache/incubator-kie-tools/pull/2682)
10. ✅ FIXED: ~Create and commit a per-repo list of files to be ignored by Apache RAT~ (see https://github.com/apache/incubator-kie-issues/issues/1613).
11. ✅ FIXED: ~Lots of `[WARNING] Could not validate integrity of download from http://172.17.0.2/` when using `maven-m2-repo-via-http` during `kie-tools` build.~ (Fixed for 10.1+, see: https://github.com/apache/incubator-kie-tools/commit/b6b6d3aebbaa12bf1ce538cc51b46da533adc6ea)
12. ✅ FIXED: ~Had to install `'requests<2.32.0'` with `python -m pip install 'requests<2.32.0'` before building `kogito-images`, otherwise it didn't work.~ (Fixed for 10.1+ since `kogito-images` has been permanently moved to `kie-tools`). 
13. ✅ FIXED: ~`999-SNAPSHOT` references found on `kogito-images@10.0.0`~ (Fixed for 10.1+ since `kogito-images` has been permanently moved to `kie-tools`)

---
### Future improvements
- https://github.com/apache/incubator-kie-issues/issues/1670

---

[1] https://kie.apache.org/docs/community/verify/

---

For reference, here are the internal voting threads:
rc1: https://lists.apache.org/thread/x1q6yz6ybmb4ym6p16bjgcdksfn900sf
rc2: https://lists.apache.org/thread/t72b95d3q1qvcyd7lbqkrt8cdx2cgsp2
rc3: https://lists.apache.org/thread/nxx66ccognnk8fozt4nk11z7g57c7fnb
rc4: https://lists.apache.org/thread/lnrx61q01n8pszqymcfqw90cq4r6mmdq

**Comment by tiagobento** [comment]
@tkobayas Can you help me understand this quote from https://lists.apache.org/thread/l7gx1wc1lfhkoxg1kwy2pzyp0nv9l2fl?

`[x] No compiled archives bundled in source archive. <- it includes some`

What are the "compiled archives" you found on our sources? Thanks!

**Comment by tkobayas** [comment]
@tiagobento 

Under incubator-kie-10.0.0-rc2-sources directory,

All jar files:
```
$ find . -name "*.jar"
./incubator-kie-drools/kie-ci/src/test/resources/kjar/kjar-module-before.jar
./incubator-kie-drools/kie-ci/src/test/resources/kjar/kjar-module-after.jar
./incubator-kie-drools/drools-verifier/drools-verifier-drl/src/test/resources/org/drools/verifier/model.jar
./incubator-kie-drools/drools-compiler/src/test/resources/KAModelTest.jar
./incubator-kie-drools/drools-compiler/src/test/resources/primespoc.jar
./incubator-kie-drools/drools-compiler/src/test/resources/eventing-example.jar
./incubator-kie-drools/drools-compiler/src/test/resources/JarWithSourceFiles.jar
./incubator-kie-drools/drools-test-coverage/test-compiler-integration/src/test/resources/billasurf.jar
./incubator-kie-drools/drools-test-coverage/test-compiler-integration/src/test/resources/only-jar-pojo-not-kjar-no-kmodule-1.0.0.jar
./incubator-kie-drools/drools-test-coverage/test-compiler-integration/src/test/resources/kie-project-simple-1.0.0.jar
./incubator-kie-drools/drools-test-coverage/test-compiler-integration/src/test/resources/org/drools/mvel/compiler/compiler/xml/changeset/changeset.jar
./incubator-kie-drools/drools-test-coverage/test-compiler-integration/src/test/resources/testEnum.jar
./incubator-kie-drools/drools-legacy-test-util/src/test/resources/billasurf.jar
./incubator-kie-drools/efesto/efesto-core/efesto-runtime-manager/efesto-runtime-manager-core/src/test/resources/TestJar.jar
./incubator-kie-drools/efesto/efesto-core/efesto-common-api/src/test/resources/TestJar.jar
./incubator-kie-drools/efesto/efesto-core/efesto-common-core/src/test/resources/TestJar.jar
./incubator-kie-kogito-apps/.mvn/wrapper/maven-wrapper.jar
./incubator-kie-kogito-runtimes/.mvn/wrapper/maven-wrapper.jar
./incubator-kie-kogito-runtimes/kogito-codegen-modules/kogito-codegen-core/src/test/resources/empty.jar
./incubator-kie-kogito-runtimes/quarkus/integration-tests/integration-tests-quarkus-gradle/integration-tests-quarkus-gradle-project/gradle/wrapper/gradle-wrapper.jar
./incubator-kie-tools/packages/stunner-editors/errai-ui/src/test/resources/less.jar
```

jar files containing .class files: 
~~~
$ find . -name "*.jar" -exec sh -c 'unzip -l "{}" | grep -q "\.class" && echo {}' \;
./incubator-kie-drools/drools-verifier/drools-verifier-drl/src/test/resources/org/drools/verifier/model.jar
./incubator-kie-drools/drools-compiler/src/test/resources/KAModelTest.jar
./incubator-kie-drools/drools-compiler/src/test/resources/primespoc.jar
./incubator-kie-drools/drools-compiler/src/test/resources/eventing-example.jar
./incubator-kie-drools/drools-compiler/src/test/resources/JarWithSourceFiles.jar
./incubator-kie-drools/drools-test-coverage/test-compiler-integration/src/test/resources/billasurf.jar
./incubator-kie-drools/drools-test-coverage/test-compiler-integration/src/test/resources/only-jar-pojo-not-kjar-no-kmodule-1.0.0.jar
./incubator-kie-drools/drools-test-coverage/test-compiler-integration/src/test/resources/testEnum.jar
./incubator-kie-drools/drools-legacy-test-util/src/test/resources/billasurf.jar
./incubator-kie-kogito-apps/.mvn/wrapper/maven-wrapper.jar
./incubator-kie-kogito-runtimes/.mvn/wrapper/maven-wrapper.jar
./incubator-kie-kogito-runtimes/quarkus/integration-tests/integration-tests-quarkus-gradle/integration-tests-quarkus-gradle-project/gradle/wrapper/gradle-wrapper.jar
~~~

I thought that test resources are acceptable. Should they be changed? (e.g. generate the jars during maven build)

**Comment by tiagobento** [comment]
@tkobayas Hi! Just reminding you of the existence of this EPIC. I'm trying to keep it up-to-date, but if you find something that is not here, please feel free to edit it's description directly! Thank you! 😊
