### ISSUE TITLE
EPIC - SonataFlow Management Console on cluster improvements

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-issues#1559]
Currently, the SonataFlow Management Console attempts to trigger workflows using internal Endpoint URLs returned by the Data Index (DI). These URLs are not accessible from outside the cluster, leading to errors when users attempt to initiate workflows through the console.

- [x] https://github.com/apache/incubator-kie-tools/issues/2696
- [x] https://github.com/apache/incubator-kie-tools/issues/2695
- [x] https://github.com/apache/incubator-kie-tools/issues/3156
- [x] https://github.com/apache/incubator-kie-tools/issues/2712
- [x] https://github.com/apache/incubator-kie-kogito-docs/issues/681
- [x] https://github.com/apache/incubator-kie-tools/issues/2649

**Comment by fantonangeli** [comment]
Closed as not planned
