### ISSUE TITLE
EPIC - [Serverless Web Tools] Deploy Workflows on OpenShift via operator

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-issues#1565]
Currently, the workflow application is deployed via a custom builder image. Alternatively, the deployment must be done via the operator, which requires the operator to be installed in the target cluster.
 
 Tasks
- [x] https://github.com/apache/incubator-kie-tools/issues/2701
- [x] https://github.com/apache/incubator-kie-tools/issues/2702
- [x] https://github.com/apache/incubator-kie-tools/issues/2703

**Comment by ricardozanini** [comment]
Serverless Web Tools won't be integrated with the SonataFlow at this time, we can rethink this in the future. Closing for now.
