### ISSUE TITLE
EPIC - Knative CLI Plugin 2024 - Q4 - 2025 - Q1

### ISSUE THREAD

**Issue by treblereel** [apache/incubator-kie-issues#1583]
Next milestone of KN Workflow CLI plugin. Comprehends:
- [x] https://github.com/apache/incubator-kie-issues/issues/1584
- [x] https://github.com/apache/incubator-kie-issues/issues/1586
- [x] https://github.com/apache/incubator-kie-issues/issues/1589
- [x] https://github.com/apache/incubator-kie-tools/issues/2718
- [x] https://github.com/apache/incubator-kie-tools/issues/2630
- [x] https://github.com/apache/incubator-kie-issues/issues/1526
- [x] https://github.com/apache/incubator-kie-issues/issues/1647
- [x] https://github.com/apache/incubator-kie-tools/issues/2623
- [x] https://github.com/apache/incubator-kie-issues/issues/1769
- [x] https://github.com/apache/incubator-kie-issues/issues/1846
- [x] https://github.com/apache/incubator-kie-issues/issues/1799
