### ISSUE TITLE
EPIC - Migrate Serverless Logic Web Tools Quarkus Accelerator repository to `kie-tools`

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-issues#1639]
Migrate the **Serverless Logic Web Tools Quarkus Accelerator** repository (currently on https://github.com/kubesmarts/sandbox-deployment/tree/quarkus-accelerator) to the `kie-tools` repository. 

**Tasks:**
- [ ] Create a new Apache repository named `incubator-kie-serverless-logic-web-tools-accelerator-quarkus` as a template repository
- [x] https://github.com/apache/incubator-kie-tools/issues/2769
- [ ] Make sure `main`'s `daily-dev` (https://ci-builds.apache.org/job/KIE/job/kie-tools/job/main/job/kie-tools-daily-dev-publish/) is publishing to the main branch correctly.
- [ ] Delete the old `quarkus-accelerator` branch from https://github.com/kiegroup/serverless-logic-sandbox-deployment

**Comment by porcelli** [comment]
@tiagobento I understand the concept of moving this, but where is this used? afaik the only UI that uses this is today downstream. 

actually I don't even understand the reason for this issue.

**Comment by tiagobento** [comment]
SLWT's source code is currently hosted in kie-tools, and @ricardozanini's proposal talks about replacing start.kubesmarts.org with a downstream, not remove anything from Apache KIE, AFAIK.

This issue is similar to the one we had for making kie-sandbox-quarkus-accelerator a read-only repo, with the source hosted in kie-tools as a normal package.

**Comment by tiagobento** [comment]
@porcelli See

- https://github.com/apache/incubator-kie-issues/issues/1090

**Comment by tiagobento** [comment]
@fantonangeli I guess we can close this and the subtasks due to the 10.3.x+ stream?

**Comment by fantonangeli** [comment]
@tiagobento yes I agree we can close it
