### ISSUE TITLE
EPIC - Migrate `kie-samples` to `kie-tools` and rename to `serverless-logic-web-tools-samples`

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-issues#1640]
Migrate the **`kie-samples`** repository (currently on [kubesmarts/sandbox-catalog](https://github.com/kubesmarts/sandbox-catalog)) to the `kie-tools` repository. 

### **Tasks:**
- [ ] Create a new Apache repository named `incubator-kie-serverless-logic-web-tools-samples` as a template repository.
- [x] https://github.com/apache/incubator-kie-tools/issues/2770
- [ ] Make sure `main`'s `daily-dev` https://ci-builds.apache.org/job/KIE/job/kie-tools/job/main/job/kie-tools-daily-dev-publish/ is publishing the `serverless-logic-web-tools-samples` package correctly.
- [ ] Delete the old `kie-samples` repository from `kiegroup` after migration is complete.

**Comment by tiagobento** [comment]
@fantonangeli I guess we can close this and the subtasks due to the 10.3.x+ stream?
