### ISSUE TITLE
Rewrite the SceSim Editor in React, using the BeeTable

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#201]
```[tasklist]
### Tasks
- [ ] https://github.com/kiegroup/kie-issues/issues/384
- [ ] https://github.com/kiegroup/kie-issues/issues/385
- [ ] Test Scenario Editor: Integration with DMN marshaller
- [ ] Test Scenario Editor: Load/Creation management
- [ ] Test Scenario Editor: Settings Dock
- [ ] Test Scenario Editor: Cheatsheet Dock
- [ ] Test Scenario Editor: Facts selection Dock
- [ ] Test Scenario Editor: Grid integration
- [ ] Test Scenario Editor: Background Grid integration
```

**Comment by yesamer** [comment]
@tiagobento The scope of this 201 ticket, was to act as a EPIC. Considering you created 453, I propose to close this ticket and use 453 for that scope.

**Comment by yesamer** [comment]
Moved to https://github.com/kiegroup/kie-issues/issues/453
