### ISSUE TITLE
Enable autocomplete suggestions for Literal Expressions and Decision Table input cells on DMN Editor's Boxed Expression Editor

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#206]
```[tasklist]
### Subtasks
- [ ] FEEL Autocompletions should offer Input Data nodes names
```

```[tasklist]
### Acceptance criteria
- [ ] Write a nice description for this issue.
- [ ] Add acceptance criteria here.
```

**Comment by dmitry-buykin** [comment]
Hi @tiagobento, any updates on this task? We tried to implement the same feature on top of the https://github.com/kiegroup/kie-tools/blob/main/packages/feel-input-component/showcase/FeelService.ts#L25-L58, but I found this task and I think it would be great if it will be done as part of KIE Tools changes.

**Comment by tiagobento** [comment]
@dmitry-buykin We're currently almost done with #159.. the infrastructure we're building for it will be leveraged for this task as well. We expect that after #159 is done, this one will follow quickly after. Keep in mind that today the `input` "name" on a Decision Table is not being treated as an expression, despite the fact that it is. See: 
- #159
- #204 

cc @danielzhe

**Comment by dmitry-buykin** [comment]
Is it possible to use constraint values from type definitions in autocomplete? 
![image](https://github.com/apache/incubator-kie-issues/assets/138513175/0ad36982-10e7-4d6d-8c1e-00275b438e05)
![image](https://github.com/apache/incubator-kie-issues/assets/138513175/3e5aa518-6498-4e62-9c23-3213c62521bb)

**Comment by yesamer** [comment]
@dmitry-buykin Not yet.
@danielzhe That is a great suggestion, do we already have a ticket for that?

**Comment by dmitry-buykin** [comment]
> @dmitry-buykin Not yet. @danielzhe That is a great suggestion, do we already have a ticket for that?
I found a similar feature which was abandoned several years ago https://issues.redhat.com/browse/KOGITO-4630
