### ISSUE TITLE
Investigate DMN TCK failures in Drools

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#357]
Investigate Drools TCK failures that are highlighted here https://github.com/dmn-tck/tck/pull/566/files#diff-54ac8863a31a3ff3c46c9cc4a6a64f66db0fc1593b6d8dd846c26422c8d384abL1179 (those that switched from SUCCESS to ERROR)

Initial status with 999-SNAPSHOT version: [ERROR] Tests run: 6368, Failures: 0, **Errors: 86**, Skipped: 0
Current status with 999-SNAPSHOT version: [ERROR] Tests run: 6682, Failures: 0, **Errors: 20**, Skipped: 0

- [x] https://github.com/apache/incubator-kie-issues/issues/1323 (**12** tests fixed) 
- [x] https://github.com/apache/incubator-kie-issues/issues/1325 (**8**  tests fixed)
- [x] https://github.com/apache/incubator-kie-issues/issues/1326 (**6** tests fixed) 
- [x] https://github.com/apache/incubator-kie-issues/issues/1330 (**8** tests fixed)
- [x] https://github.com/apache/incubator-kie-issues/issues/1345 (**2** tests fixed)
- [x] https://github.com/apache/incubator-kie-issues/issues/1350 (Will fix **1** test)
- [x] https://github.com/apache/incubator-kie-issues/issues/1356 (**24** tests fixed)
- [x] https://github.com/apache/incubator-kie-issues/issues/1367 (**1** test fixed)
- [x] https://github.com/apache/incubator-kie-issues/issues/1409 (**5** tests fixed)
- [x] https://github.com/apache/incubator-kie-issues/issues/1411 (**1** test fixed)
- [x] https://github.com/apache/incubator-kie-issues/issues/1448 (**10** tests fixed)
- [x] https://github.com/apache/incubator-kie-issues/issues/1410 (Will fix **1** test)
- [x] https://github.com/apache/incubator-kie-issues/issues/1536 
- [x] https://github.com/apache/incubator-kie-issues/issues/1546 (Will fix **4** tests)
- [x] #1646
- [x] https://github.com/apache/incubator-kie-issues/issues/1743 (Will fix **6** tests)
- [x] https://github.com/apache/incubator-kie-issues/issues/1744 (Will fix **3** tests)
- [x] #1752 (Will fix 1 test)
- [x] #1771 (Will fix 4 tests)
- [x] #1794 (Should fix 5 tests)
- [x] #1829 ( **2** tests fixed)
- [x] #1811
- [x] #1831
- [x] #1841 ( **4** tests fixed)
- [x] #2017 ( **6** tests fixed)
- [x] #2028 ( **5** tests fixed)
- [x] #2133 ( **1** tests fixed)

Nice to have:
- [ ] https://github.com/apache/incubator-kie-issues/issues/1415

Acceptance criteria: 
- The highlighted tests as new errors pass.

**Comment by baldimir** [comment]
This issue is related to the failures from TCK tests https://github.com/apache/incubator-kie-issues/issues/69

**Comment by tiagobento** [comment]
@yesamer Thank you for looking into this! If I may, can you please help me understand these two points?
1. Why we're not tackling the last bullet-point `Time-based format output (12:12:12) returns no-seconds when they're equal to 00 (eg. 10:00:00 returns 10:00) (Will fix 2 test2)`?
2. Is there any place describing how to execute the DMN TCK tests for us? Would be good to plan a periodic execution to see if we didn't introduce any regressions...

**Comment by yesamer** [comment]
@tiagobento 
1. It seems that DMN 1.6 will revisit the time/date specifications. We agreed with @baldimir and @gitgabrio to temporarily keep that point on hold for that reason. 
2. We can run them in the TCK repo https://github.com/dmn-tck/tck/tree/master/runners. But it should be possible to run them on drools side too. Once we fix all of them, I would like to run them at every PR that touches DMN-related code.

**Comment by yesamer** [comment]
I'm going to close this epic, as we fixed most of the issue (currently 2 failures only remain - there is an ongoing clarification).
thank you all for the effort!
