### ISSUE TITLE
EPIC - Transfer `kiegroup` repositories to the `apache` organization

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#428]
The list of repositories has been identified by #419 

- [x] Transfer to Apache the [drools](https://github.com/kiegroup/drools) repository
- [x] Transfer to Apache the [kogito-runtimes](https://github.com/kiegroup/kogito-runtimes) repository
- [x] Transfer to Apache the [kogito-apps](https://github.com/kiegroup/kogito-apps) repository
- [x] Transfer to Apache the [kogito-examples](https://github.com/kiegroup/kogito-examples) repository
- [x] Transfer to Apache the [kogito-docs](https://github.com/kiegroup/kogito-docs) repository
- [x] Transfer to Apache the [kogito-images](https://github.com/kiegroup/kogito-images) repository
- [x] Transfer to Apache the [kogito-operator](https://github.com/kiegroup/kogito-operator) repository
- [x] Transfer to Apache the [kogito-website](https://github.com/kiegroup/kogito-website) repository
- [x] Transfer to Apache the [kogito-pipelines](https://github.com/kiegroup/kogito-pipelines) repository
- [x] Transfer to Apache the [kie-benchmarks](https://github.com/kiegroup/kie-benchmarks) repository
- [x] Transfer to Apache the [optaplanner](https://github.com/kiegroup/optaplanner) repository
- [x] Transfer to Apache the [kogito-serverless-operator](https://github.com/kiegroup/kogito-serverless-operator) repository
- [x] Transfer to Apache the [optaplanner-quickstarts](https://github.com/kiegroup/optaplanner-quickstarts) repository
- [x] Transfer to Apache the [kie-docs](https://github.com/kiegroup/kie-docs) repository
- [x] Transfer to Apache the [kogito-benchmarks](https://github.com/kiegroup/kogito-benchmarks) repository
- [x] #700 
- [ ] #701 
- [ ] #702

**Comment by ederign** [comment]
I just would like to double-check that we are planning to keep the commit history of the repositories.

@tiagobento did a similar thing when we moved stunner codebase inside kie-tools in the past and can give us pointers.

**Comment by tiagobento** [comment]
@ederign I think in this case we just go to Settings and do a "transfer ownership"...

**Comment by porcelli** [comment]
@mareknovotny This likely will have an impact on product builds. 

I think the best option for minimizing impact is to move the repos and, at the same time, create a mirror of the moved repositories in kiegroup org. 

This might require some re-configuration.

**Comment by mareknovotny** [comment]
or just copy/clone them instead of Transfer them /that is possible only on github org to org/

Do we know where the target Apache git repos will live? Is that github Apache org or completely inside Apache git infra? @porcelli @mdproctor

**Comment by porcelli** [comment]
One big advantage of transferring is to preserve the metadata associated with repositories, like the number of forks and stars... we wouldn't start from scratch.
Given that the future of those codebases will be on Apache, I think it makes more sense to preserve such information in the transfer process.

**Comment by radtriste** [comment]
what about `optaplanner-website` and `drools-website` ?

**Comment by porcelli** [comment]
@lazarotti @mdproctor @krisv could you chime in related to the repos @radtriste just mentioned?

**Comment by porcelli** [comment]
@radtriste I think we could postpone the -website repositories for phase 2. as seems that we'll have some challenges with the apache and github pages.

**Comment by radtriste** [comment]
what about `kie-docs` and `kogito-docs` ?
don't we have the same issue there ?

**Comment by porcelli** [comment]
I'd argue that the docs repos are slightly different, as we would still be able to contribute in updating docs for new features or fixes... even if we have problems to publish it

**Comment by porcelli** [comment]
closing this epic for now, the remaining repos are tracked individually
