### ISSUE TITLE
EPIC - The new React-based DMN Editor!

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#439]
### 1st phase (Parity with existing GWT-based DMN Editor & push to `main`)
- [x] https://github.com/kiegroup/kie-issues/issues/165
- [x] https://github.com/kiegroup/kie-issues/issues/440
- [x] https://github.com/kiegroup/kie-issues/issues/577
- [x] https://github.com/kiegroup/kie-issues/issues/443
- [ ] https://github.com/kiegroup/kie-issues/issues/213
- [ ] https://github.com/kiegroup/kie-issues/issues/4
- [ ] https://github.com/kiegroup/kie-issues/issues/164
- [ ] https://github.com/kiegroup/kie-issues/issues/219
- [ ] https://github.com/kiegroup/kie-issues/issues/436
- [ ] https://github.com/kiegroup/kie-issues/issues/233
- [ ] https://github.com/kiegroup/kie-issues/issues/286
- [ ] https://github.com/kiegroup/kie-issues/issues/269
- [ ] https://github.com/kiegroup/kie-issues/issues/218
- [ ] https://github.com/kiegroup/kie-issues/issues/121

### 2nd phase (DMN 1.4 and 1.5)
BEE
- [x] https://github.com/kiegroup/kie-issues/issues/239
- [x] https://github.com/kiegroup/kie-issues/issues/904
- [x] https://github.com/apache/incubator-kie-issues/issues/672
- [x] https://github.com/kiegroup/kie-issues/issues/455
- [ ] https://github.com/kiegroup/kie-issues/issues/236
- [x] https://github.com/kiegroup/kie-issues/issues/237
- [x] https://github.com/kiegroup/kie-issues/issues/238
- [x] https://github.com/kiegroup/kie-issues/issues/235

Diagram
- [x] https://github.com/apache/incubator-kie-issues/issues/785
- [x] https://github.com/kiegroup/kie-issues/issues/232
- [x] https://github.com/apache/incubator-kie-issues/issues/669
- [x] https://github.com/kiegroup/kie-issues/issues/234

### 3rd phase (Hardening & testing)
- [x] https://github.com/kiegroup/kie-issues/issues/441
- [x] https://github.com/kiegroup/kie-issues/issues/442

### 4th phase (Distributing & next steps)
- [x] https://github.com/kiegroup/kie-issues/issues/450

### Moved to https://github.com/apache/incubator-kie-issues/issues/625
- ~https://github.com/kiegroup/kie-issues/issues/448~
- ~https://github.com/kiegroup/kie-issues/issues/449~ 
- ~https://github.com/kiegroup/kie-issues/issues/447~

**Comment by tiagobento** [comment]
Several updates were done to the tasks here... In special, I created this one: 
- #577 

which actually has a lot of smaller tasks inside. I plan to publish the WIP React-based DMN Editor somewhere on GitHub Pages for people to try it and provide feedback.

Some tasks listed here were closed, as they'll be addressed as part of #577.

**Comment by tiagobento** [comment]
Moved
- https://github.com/apache/incubator-kie-issues/issues/388

to

- #625

**Comment by tiagobento** [comment]
I'm gonna be using this issue for community feedback on the new DMN Editor.

### Please feel free to comment here, and thanks for giving us feedback!

**Comment by jaimeizuz** [comment]
Hi! Maybe a silly question, but I've just started using the new DMN editor and... how do I delete a node in a diagram? "Supr" key doesn't seem to work anymore... Additionally, the "trash" icon is no longer there...

**Comment by jaimeizuz** [comment]
Another thing I've realized, looks like there are some schema validation issues. I've created a very simple DMN model, it's a Hello World. Validation have shows a couple of errors:

![image](https://github.com/apache/incubator-kie-issues/assets/138981666/b8c6ff15-a8c8-4480-8a83-887e7f390fe4)

**Comment by ljmotta** [comment]
Hi @jaimeizuz, thanks for your questions. Regarding the node removal, you can use the backspace key on windows and linux, and the delete key on Mac. It appears the keyboard shortcuts panel (shift + /) is missing a few of them. I'll create an issue to track this. (https://github.com/apache/incubator-kie-issues/issues/793)

Now, to validate a diagram we use the `extended-services`. Unfortunately, the `extended-services` still doesn't support the DMN 1.5, so we don't have validations for the new editor yet, but we're already working on this feature.

**Comment by jaimeizuz** [comment]
@ljmotta many thanks for your quick response! The backspace worked fine. Just for curiosity, is there any reason for that change in the node removal? I know it's not a big deal, but people used to the Del key will find it strange...

**Comment by tiagobento** [comment]
@jaimeizuz That's an overlook from our part. The `backspace` key is the default used by ReactFlow, so we stuck to it and didn't add any additional behavior. We can add it no problem. Thanks a lot for the feedback!

**Comment by jaimeizuz** [comment]
@tiagobento thanks for the clarification, and very good job! I'll be collaborating with some clients in the implementation of real-life DMN models the next 3 months so I'll try to find the time to give you as much feedback as I can!

By the way, it will be nice indeed if the DEL key can be added at some point:)

**Comment by tarilabs** [comment]
Thanks @tiagobento for the headsup and congrats to the Team this new editor looks awesome!!

Some random early comments:
- appreciate the toggle option for Type dropdown on the node
- not clear what "enable style" toggle actually do? 🤔 
- appreciate the highlight hierarchy on node selection
- really LOVE you included grouping and appreciate A LOT by default it would group selected nodes; this feature was always missing and in cases is extremely helpful for a Modeler (it doesn't affect runtime, but it's a powerful feature for Modeling/Presentation/Documentation, etc)
- if I drop in a given DRD a Decision Service node which was defined in another DRD, it "freezes in place" and in general I would maybe reconsider this when you can define collapsible Decision Service?
- I would consider allowing to shrink vertically nodes further, especially Text Annotation node (say I enter 1 line, I cannot make it shorter vertically from the default vertical size); the default node size when dropped in the canvas are fine imho, I would only consider allowing to shrink further.
- if I move the mouse on an edge it "suggest" adding a bend, but clicking to add a bend does not do any effect; is this expected? (maybe is not implemented yet, just thought of mentioning)

**Comment by tiagobento** [comment]
Hi @tarilabs! Thanks a lot for finding some time to look at the new Editor, your feedback is really important! Some answer to your comments below:

---

> - not clear what "enable style" toggle actually do? 🤔

It turns on/off node custom styles... Imagine you want to look at the diagram without colors and custom fonts etc.

---

> - if I drop in a given DRD a Decision Service node which was defined in another DRD, it "freezes in place" and in general I would maybe reconsider this when you can define collapsible Decision Service?

Right, good catch! This is a bug happening because the encapsulated/output decisions are not included together with the DMN.

---

> - I would consider allowing to shrink vertically nodes further, especially Text Annotation node (say I enter 1 line, I cannot make it shorter vertically from the default vertical size); the default node size when dropped in the canvas are fine imho, I would only consider allowing to shrink further.

Right, good feedback. Luckily this is really easy to change! I'll make it happen.

---

> - if I move the mouse on an edge it "suggest" adding a bend, but clicking to add a bend does not do any effect; is this expected? (maybe is not implemented yet, just thought of mentioning)

It works with a double-click.. But it only works on Chrome for now as far as I remember.. there's some weird CSS/SVG rendering issues happening in Firefox and Safari.
