### ISSUE TITLE
EPIC - The new React-based SceSim Editor!

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#453]
### Tasks 1th Phase
- [x] https://github.com/kiegroup/kie-issues/issues/384
- [x] https://github.com/kiegroup/kie-issues/issues/385
- [x] https://github.com/kiegroup/kie-issues/issues/538
- [x] https://github.com/kiegroup/kie-issues/issues/523
- [x] https://github.com/kiegroup/kie-issues/issues/561
- [x] https://github.com/kiegroup/kie-issues/issues/580
- [x] #629 
- [x] #665
- [x] #737
- [x] #738
- [x] #1463
- [x] #1511
- [x] #1481
- [x] #970
- [x] #1514
- [x] #1552
- [x] #1844

### Known Issues

- [x] #1855
- [x] #1353
- [x] #1807
- [x] #1808
- [ ] #1809 
- [x] #1810 
- [x] #1870
- [x] #1871
- [x] #1875 
- [x] #1879 
- [x] #1919

### Tasks 2th Phase
- [ ] Test Scenario Editor: Collections management
- [ ] The BeeTable data cells should be able to contain placeholder values
- [ ] Shouldn't be possible to assign data to Undefined columns (eg. INSTANCE-1 / PROPERTY-1 columns)
- [ ] #735 
- [ ] #1342
- [ ] #1354
- [ ] #1355
 - [ ] #1363
- [ ] #782
- [ ] #1847
- [ ] #1861
