### ISSUE TITLE
EPIC - Continuous improvements for DMN/FEEL language features (2H2023 iteration)

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#454]
### Q3
- [x] https://github.com/kiegroup/kie-issues/issues/35
- [x] https://github.com/kiegroup/kie-issues/issues/159
- [x] https://github.com/kiegroup/kie-issues/issues/391
- [x] https://github.com/kiegroup/kie-issues/issues/420
- [x] https://github.com/kiegroup/kie-issues/issues/431
- [x] https://github.com/kiegroup/kie-issues/issues/510
- [x] https://github.com/kiegroup/kie-issues/issues/589
- [x] https://github.com/kiegroup/kie-issues/issues/590

### Q4
- [x] https://github.com/apache/incubator-kie-issues/issues/636
- [x] https://github.com/apache/incubator-kie-issues/issues/603
- [x] https://github.com/kiegroup/kie-issues/issues/374
- [x] https://github.com/kiegroup/kie-issues/issues/206
- [x] https://github.com/kiegroup/kie-issues/issues/539

### Roll-over section (to be moved to the next iteration)
* Moved to https://github.com/apache/incubator-kie-issues/issues/794
