### ISSUE TITLE
EPIC - Continuous improvements for VS Code extensions (2H2023 iteration)

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#456]
### Q3
- None

### Q4
- [x] https://github.com/kiegroup/kie-issues/issues/366
- [x] https://github.com/apache/incubator-kie-issues/issues/633
- [x] https://github.com/apache/incubator-kie-issues/issues/685

### Roll-over section (to be moved to the next iteration)
- Moved to https://github.com/apache/incubator-kie-issues/issues/795

**Comment by jomarko** [comment]
I know we have some ticket for better sync of VS Code menu items, like save, undo with KIE editors, should we link such ticket into this epic?

**Comment by tiagobento** [comment]
This one?
- https://github.com/kiegroup/kie-issues/issues/217

Yep, good catch.
