### ISSUE TITLE
EPIC - Highlight DMN Runner execution data directly on the DMN Editor, especially on Decision Tables

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#459]
### Tasks
- [ ] https://github.com/kiegroup/kie-issues/issues/462
- [ ] https://github.com/kiegroup/kie-issues/issues/461
- [ ] https://github.com/kiegroup/kie-issues/issues/463
- [ ] https://github.com/kiegroup/kie-issues/issues/464

**Comment by jomarko** [comment]
I tend to think we can close this ticket and linked tasks as the evaluation highlights feature is in? 


https://github.com/apache/incubator-kie-issues/issues/1823
