### ISSUE TITLE
EPIC - Continuous improvements for the KIE Tools monorepo (2H2023 iteration)

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#466]
### Q3
- [x] https://github.com/kiegroup/kie-issues/issues/552
- [x] https://github.com/kiegroup/kie-issues/issues/488
- [x] https://github.com/kiegroup/kie-issues/issues/329

### Q4
- [x] https://github.com/apache/incubator-kie-issues/issues/630

### Roll-over section (to be moved to the next iteration)
- Moved to https://github.com/apache/incubator-kie-issues/issues/797
