### ISSUE TITLE
EPIC - Upgrade PatternFly from `v4` to `v5` on `kie-tools`

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#468]
PatternFly's migration guide: https://www.patternfly.org/get-started/upgrade/#patternfly-5

Issues in this epic:

- [x] https://github.com/apache/incubator-kie-tools/issues/2642
- [x] https://github.com/apache/incubator-kie-tools/issues/2641
- [x] https://github.com/apache/incubator-kie-issues/issues/1947

---

Related:
- https://github.com/apache/incubator-kie-tools/issues/1877
- https://github.com/apache/incubator-kie-tools/pull/1921

**Comment by yesamer** [comment]
**uniforms-patternfly** module has been updated by @lordrip here https://github.com/KaotoIO/kaoto-next/tree/main/packages/uniforms-patternfly
Thank you, Ricardo!

**Comment by lordrip** [comment]
@yesamer, I moved the library to a standalone repository https://github.com/KaotoIO/uniforms-patternfly. The idea is to have independent versioning after each merge to the main branch and also make it easier to bring the library back kie-tools when makes sense.

**Comment by jomarko** [comment]
Hello @lordrip @yesamer @tiagobento , should we do the same for `kogito-apps` react codebase?

**Comment by lordrip** [comment]
Hi @jomarko, what do you mean by the same?

**Comment by jomarko** [comment]
@lordrip upgrade patternfly dependencies from 4.x to 5.x for `kogito-apps`

**Comment by tiagobento** [comment]
For anyone interested on the comments above, everything related to React has been moved from `kogito-apps` to `kie-tools`.

**Comment by fantonangeli** [comment]
@tiagobento I generated the full list of components to updated on kie-tools. I used the command:
`pnpm -rc exec "[ -d 'src' ] && npx @patternfly/pf-codemods@latest ./src || exit 0" >pf-codemods-v5.logs`

[Here is the list of files](https://docs.google.com/spreadsheets/d/1V1LxLuu4Vv6-V8ncOMKH7vXHog5fQiwcnMw-glLq32k)
[Here is the full logs](https://docs.google.com/document/d/1ywohWR_qYIuzBvqafrgNHtQEygT_x_s1SI7O7fqUXxw)

**Comment by tiagobento** [comment]
@fantonangeli Nice. I guess that's gonna be the way to achieve this... Trying some things to find out what's the best strategy to tackle it. I guess it's fine to upgrade in parts.. we just need to know what packages will be done on each part

**Comment by fantonangeli** [comment]
@tiagobento I think we can create a new `patternfly-v5-upgrade` branch, configuring syncpack to allow Patternfly v4 and v5 together.
Then we upgrade packages by packages or block of packages, depending on how many files needs to be updated.
Then open the final PR to `main` branch.
WDYT?

**Comment by lordrip** [comment]
Hi @tiagobento @fantonangeli, I think you are aware, but just in case, this is the fork of `uniforms-patternfly` that we did for Kaoto :point_right:  https://github.com/KaotoIO/uniforms-patternfly using patternfly v5.

The reason why I mention it is because maybe it could simplify the update process a bit because perhaps you could migrate one application at a time (_I don't know if this is something that you're after_), despite the application using `uniforms`, otherwise I guess you would need to upgrade uniforms first. :thinking:

**Comment by fantonangeli** [comment]
Thank you @lordrip for your very nice work.
I think we can use your uniforms-patternfly  to update @kie-tools/uniforms-patternfly

**Comment by jomarko** [comment]
Hi everyone, I would like to understand better the approach we are going to proceed. To me, it sounds we discuss currently these options:
- upgrade patternfly from v4 to v5 in small steps directly in kie-tools packages, what may bring a problem of parallel usage of different versions?
- replace `kie-tools/uniforms-patternfly` with `KaotoIO/uniforms-patternfly`, I am not sure if this is somehow conforming to kie-tools strategy, I mean there is effort to have kie-tools as one mono repo

thank you for any comment, I am always happy when similar upgrades are achieved

**Comment by fantonangeli** [comment]
Hi @jomarko ,
- upgrade patternfly from v4 to v5 in small steps directly in kie-tools packages, what may bring a problem of parallel usage of different versions?
We are still defining the groups of packages, possibly isolated, to update, limiting the impact to other groups and how to proceed. 

- replace kie-tools/uniforms-patternfly with KaotoIO/uniforms-patternfly, I am not sure if this is somehow conforming to kie-tools strategy, I mean there is effort to have kie-tools as one mono repo
I was referring to import their code to `kie-tools/packages/uniform-patternfly` If it's an "ok way to proceed". Of course we will set again the folders following the kie-tools style.
