### ISSUE TITLE
EPIC - Continuous improvements for KIE Sandbox (2H2023 iteration)

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#482]
### Q3
- [x] https://github.com/kiegroup/kie-issues/issues/101
- [x] https://github.com/kiegroup/kie-issues/issues/398

### Q4
- [x] https://github.com/apache/incubator-kie-issues/issues/743

### Roll-over section (to be moved to the next iteration)
- Moved to https://github.com/apache/incubator-kie-issues/issues/798
