### ISSUE TITLE
EPIC - Continuous improvements for the DMN Editor (1H2024 iteration)

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#625]
Next: https://github.com/apache/incubator-kie-issues/issues/1419

### Q1
- [x] When external nodes are deleted on included models, the DMN Editor should display an unknown node.
- [x] ~Double-clicking an external Decision Service node is crashing the DMN Editor~. Could not reproduce anymore (Feb 1st, 2024)
- [x] #831
- [x] https://github.com/apache/incubator-kie-issues/issues/870
- [x] https://github.com/apache/incubator-kie-issues/issues/663
- [x] https://github.com/apache/incubator-kie-issues/issues/664
- [x] https://github.com/apache/incubator-kie-issues/issues/793
- [x] https://github.com/apache/incubator-kie-issues/issues/401... We probably need to refactor `ExpressionDefinition` to not exist anymore, and make the BEE use the model from `dmn-marshaller` instead... See https://github.com/apache/incubator-kie-issues/issues/455
- [x] #879
- [x] https://github.com/apache/incubator-kie-issues/issues/842
- [x] #880
- [x] #881
- [x] #914
- [x] #885
- [x] #928
- [x] #944
- [x] #883

### Decision Services & multiple DRDs (see #870)
- [x] #888
- [x] #894
- [x] #972
- [x] https://github.com/apache/incubator-kie-issues/issues/1298

### Q2
- [x] #937
- [x] https://github.com/apache/incubator-kie-issues/issues/451
- [x] #882
