### ISSUE TITLE
EPIC - Release 10.0.0

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#707]
tracking release 10.0.0

- [x] #417 
- [x] #413 
- [x] #605 
- [x] https://github.com/apache/incubator-kie-issues/issues/967
- [x] https://github.com/apache/incubator-kie-issues/issues/1217
- [ ] https://github.com/apache/incubator-kie-issues/issues/1210
- [x] #1231
- [ ] Document the release procedure
- [ ] Branch out and release a Release Candidate
- [ ] KIE vote + Sanity checks
- [ ] IPMC vote
- [ ] Publish release artifacts to https://dist.apache.org/repos/dist/release/incubator/kie/10.0.0
- [ ] Publish release artifacts to non-official channels (NPM, Websites etc)
- [ ] Announcement
