### ISSUE TITLE
EPIC - Continuous improvements for DMN/FEEL language features (1H2024 iteration)

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#794]
Next: https://github.com/apache/incubator-kie-issues/issues/1421

## Q1
- [x] https://github.com/apache/incubator-kie-issues/issues/455
- [x] https://github.com/kiegroup/kie-issues/issues/401
- [x] https://github.com/kiegroup/kie-issues/issues/536

## Q2
- [x] #1177
- [x] #1176
- [x] #1178
