### ISSUE TITLE
EPIC - Continuous improvements for the KIE Tools monorepo (1H2024 iteration)

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#797]
Next: https://github.com/apache/incubator-kie-issues/issues/1424

## Q1
- [x] https://github.com/apache/incubator-kie-issues/issues/634
- [x] https://github.com/apache/incubator-kie-issues/issues/393

## Q2
- [x] https://github.com/apache/incubator-kie-issues/issues/1113
- [x] https://github.com/apache/incubator-kie-issues/issues/1119
- [x] https://github.com/apache/incubator-kie-issues/issues/392
- [x] https://github.com/apache/incubator-kie-issues/issues/467
- [x] https://github.com/apache/incubator-kie-issues/issues/1331
- [x] #1156
- [x] https://github.com/apache/incubator-kie-issues/issues/243
- [x] https://github.com/apache/incubator-kie-issues/issues/1366
