### ISSUE TITLE
EPIC - Continuous improvements for KIE Sandbox (1H2024 iteration)

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#798]
Next: https://github.com/apache/incubator-kie-issues/issues/1425

## Q1
- [x] https://github.com/kiegroup/kie-issues/issues/389
- [x] https://github.com/apache/incubator-kie-issues/issues/393

## Q2
- [x] https://github.com/apache/incubator-kie-issues/issues/408
- [x] https://github.com/kiegroup/kie-issues/issues/407
- [x] https://github.com/kiegroup/kie-issues/issues/337
- [x] https://github.com/kiegroup/kie-issues/issues/131
