### ISSUE TITLE
EPIC - Continuous improvements for E2E tests on KIE Tools (1H2024 iteration)

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#801]
Next: https://github.com/apache/incubator-kie-issues/issues/1428

## Q1
- [x] https://github.com/apache/incubator-kie-issues/issues/871
- [x] https://github.com/apache/incubator-kie-issues/issues/874

## Q2
- [x] https://github.com/kiegroup/kie-issues/issues/560
