### ISSUE TITLE
Make Drools and Kogito build reproducible

### ISSUE THREAD

**Issue by mariofusco** [apache/incubator-kie-issues#820]
In order to make our builds complaint with Apache standards they have to be configured as a reproducible according to what described here https://maven.apache.org/guides/mini/guide-reproducible-builds.html 

TODO:

1. configure` maven-artifact-plugin / project.build.outputTimestamp`
2. execute `mvn artifact:check-buildplan` (to check overall configuration)
3. execute two consecutive builds:
           1.  `mvn clean install`
           2. `mvn clean verify artifact:compare` (check against previous build)

- [x] [drools](https://github.com/apache/incubator-kie-drools/pull/5650)
- [x] [kogito-runtimes]() - (depends on https://github.com/apache/incubator-kie-issues/issues/824) (fixed by https://github.com/apache/incubator-kie-kogito-runtimes/pull/3356)
- [x] [kogito-apps]() - (depends on https://github.com/apache/incubator-kie-issues/issues/825) (fixed by https://github.com/apache/incubator-kie-kogito-apps/pull/1953)
- [x] [kogito-examples]() - (depends on https://github.com/apache/incubator-kie-issues/issues/826) (fixed by https://github.com/apache/incubator-kie-kogito-examples/pull/1854)

**Comment by mariofusco** [comment]
Implemented in Drools with https://github.com/apache/incubator-kie-drools/commit/829c28ae40155010a3a4d4085f9617d3cedccbe6
