### ISSUE TITLE
EPIC - Migrating Quarkus Dev UIs, Management Console, and Task Console from `kogito-apps` to `kie-tools`

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#967]
- [x] https://github.com/apache/incubator-kie-issues/issues/960
- [x] https://github.com/apache/incubator-kie-issues/issues/965
- [x] https://github.com/apache/incubator-kie-issues/issues/833
- [x] https://github.com/apache/incubator-kie-tools/pull/2167
- [x] #1033 
- [x] https://github.com/apache/incubator-kie-issues/issues/1052
- [x] https://github.com/apache/incubator-kie-issues/issues/966
- [x] https://github.com/apache/incubator-kie-issues/issues/963
- [x] https://github.com/apache/incubator-kie-kogito-images/pull/1753
- [x] https://github.com/apache/incubator-kie-issues/issues/961
- [x] https://github.com/apache/incubator-kie-issues/issues/1041
- [x] https://github.com/apache/incubator-kie-issues/issues/1037
- [x] https://github.com/apache/incubator-kie-issues/issues/1078
- [x] https://github.com/apache/incubator-kie-issues/issues/1096
- [x] https://github.com/apache/incubator-kie-issues/issues/962
- [x] https://github.com/apache/incubator-kie-issues/issues/1038
- [x] #1001
- [x] https://github.com/apache/incubator-kie-issues/issues/1036
- [x] _~(TODO) https://github.com/apache/incubator-kie-kogito-images/issues/1739~ Postponed to after Apache KIE 10._
- [x] https://github.com/apache/incubator-kie-issues/issues/1034
- [x] https://github.com/apache/incubator-kie-issues/issues/1035
- [x] https://github.com/apache/incubator-kie-issues/issues/1121
- [x] https://github.com/apache/incubator-kie-issues/issues/959
- [x] https://github.com/apache/incubator-kie-tools/pull/2272
