### ISSUE TITLE
EPIC - Continuous improvements for the DMN engine (2H2024 iteration)

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#997]
Tickets related to overall DMN-engine improvement.
Do not put bugs here.

### Q3
- [x] https://github.com/apache/incubator-kie-issues/issues/73
- [x] https://github.com/apache/incubator-kie-issues/issues/1104
- [x] https://github.com/apache/incubator-kie-issues/issues/855
- [x] https://github.com/apache/incubator-kie-issues/issues/1187
- [x] https://github.com/apache/incubator-kie-issues/issues/1206
- [x] https://github.com/apache/incubator-kie-issues/issues/1344
- [x] https://github.com/apache/incubator-kie-issues/issues/1370

### Q4
- None

**Comment by tiagobento** [comment]
Closed for 2H2024. Next iteration here: https://github.com/apache/incubator-kie-issues/issues/1757
